# Generated by Django 5.2.3 on 2025-11-24 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional comment about this automation step', verbose_name='Comment')),
                ('question', models.CharField(blank=True, help_text="The question this conditional answers, e.g., 'Is the user active?' It will be shown in the editor.", max_length=255, verbose_name='Question')),
                ('condition', models.JSONField(default=dict, help_text='Condition to evaluate for this conditional to evaluate. Use double curly braces {{ }} for data attribute resolution, e.g. {{ first_name }}.', verbose_name='Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SplitPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'verbose_name': 'Split Plugin',
                'verbose_name_plural': 'Split Plugins',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255, verbose_name='Name')),
                ('service', models.CharField(help_text='The service this API key is for', max_length=100, verbose_name='Service')),
                ('api_key', models.CharField(help_text='The API key or token', max_length=500, verbose_name='API Key')),
                ('description', models.TextField(blank=True, help_text='Optional notes about this API key', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active', verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['service', 'name'],
                'indexes': [models.Index(fields=['service', 'is_active'], name='djangocms_a_service_b0f21f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='djangocms_automation.automation')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('key', models.CharField(default='', max_length=64, verbose_name='Unique hash')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_automation.automation', verbose_name='Automation')),
                ('testing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangocms_automation.automationcontent', verbose_name='Testing Content')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.UUIDField(blank=True, verbose_name='Status')),
                ('paused_until', models.DateTimeField(blank=True, null=True, verbose_name='Paused until')),
                ('locked', models.IntegerField(default=0, verbose_name='Locked')),
                ('requires_interaction', models.BooleanField(default=False, verbose_name='Requires interaction')),
                ('interaction_permissions', models.JSONField(default=list, help_text='List of permissions of the form app_label.codename', verbose_name='Required permissions')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=256, verbose_name='Message')),
                ('result', models.JSONField(blank=True, default=dict, null=True, verbose_name='Result')),
                ('interaction_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Assigned group')),
                ('interaction_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Assigned user')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangocms_automation.automationaction', verbose_name='Previous action')),
                ('automation_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_automation.automationinstance')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.SlugField(help_text='Unique identifier for this trigger within the automation content. Used, e.g., if it needs to be triggered by other automation.', max_length=255, verbose_name='Slot')),
                ('type', models.CharField(default='code', max_length=100)),
                ('config', models.JSONField(default=dict, editable=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('automation_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='djangocms_automation.automationcontent')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
