# Generated by Django 5.2.3 on 2025-11-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifpluginmodel',
            name='question',
            field=models.CharField(blank=True, help_text="The question this conditional answers, e.g., 'Is the user active?' It will be shown in the editor.", max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='ifpluginmodel',
            name='condition',
            field=models.JSONField(default=dict, help_text='Condition to evaluate for this conditional to evaluate. Use double curly braces {{ }} for data attribute resolution, e.g. {{ first_name }}.', verbose_name='Condition'),
        ),
    ]
