# Generated by Django 6.0rc1 on 2025-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationinstance',
            name='initial_data',
            field=models.JSONField(default=dict, verbose_name='Initial Data'),
        ),
    ]
