# Generated by Django 6.0rc1 on 2025-11-27 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0002_automationinstance_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseActionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional comment about this automation step', verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
