# Generated by Django 5.2.3 on 2025-11-24 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0002_ifpluginmodel_question_alter_ifpluginmodel_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifpluginmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
