# Generated by Django 6.0rc1 on 2025-11-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0003_baseactionpluginmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationaction',
            old_name='status',
            new_name='plugin_ptr',
        ),
        migrations.AddField(
            model_name='automationaction',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='State'),
        ),
    ]
