# Generated by Django 6.0rc1 on 2025-11-30 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0004_rename_status_automationaction_plugin_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='djangocms_automation.automationaction', verbose_name='Parent action'),
        ),
        migrations.AddField(
            model_name='splitpluginmodel',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Optional comment about this automation step', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='splitpluginmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
