# Generated by Django 6.0rc1 on 2026-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0005_automationaction_parent_splitpluginmodel_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationaction',
            name='locked',
        ),
        migrations.AddField(
            model_name='automationinstance',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='automationinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='baseactionpluginmodel',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Field values (expressions or templates) entered in the plugin form.', verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='automationaction',
            name='plugin_ptr',
            field=models.UUIDField(blank=True, verbose_name='Plugin UUID'),
        ),
        migrations.AlterField(
            model_name='automationinstance',
            name='data',
            field=models.JSONField(default=list, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='automationinstance',
            name='initial_data',
            field=models.JSONField(default=list, verbose_name='Initial Data'),
        ),
    ]
