# Generated by Django 6.0rc1 on 2026-07-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0007_rename_actionplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateModelActionModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.baseactionpluginmodel',),
        ),
        migrations.CreateModel(
            name='LLMActionPluginModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.baseactionpluginmodel',),
        ),
        migrations.CreateModel(
            name='MailActionPluginModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.baseactionpluginmodel',),
        ),
        migrations.CreateModel(
            name='QueryModelActionModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.baseactionpluginmodel',),
        ),
        migrations.CreateModel(
            name='UpdateModelActionModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.baseactionpluginmodel',),
        ),
        migrations.CreateModel(
            name='UserInputActionPluginModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.baseactionpluginmodel',),
        ),
    ]
