# Generated by Django 6.0rc1 on 2026-07-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0008_action_proxies'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationinstance',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Caller-supplied key that prevents duplicate execution of the same event. An instance with a non-null key is unique per automation content.', max_length=255, null=True, verbose_name='Idempotency key'),
        ),
        migrations.AddConstraint(
            model_name='automationinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('automation_content', 'idempotency_key'), name='unique_idempotency_per_content'),
        ),
    ]
