# Generated by Django 6.0rc1 on 2026-08-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0011_reliability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
            ],
            options={
                'verbose_name': 'Dead letter',
                'verbose_name_plural': 'Dead letters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.automationaction',),
        ),
    ]
