# Generated by Django 6.0rc1 on 2026-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0012_deadletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=64, unique=True, verbose_name='Result id')),
                ('task_path', models.CharField(max_length=512, verbose_name='Task path')),
                ('queue_name', models.CharField(default='default', max_length=64, verbose_name='Queue')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('args', models.JSONField(default=list, verbose_name='Positional arguments')),
                ('kwargs', models.JSONField(default=dict, verbose_name='Keyword arguments')),
                ('state', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='READY', max_length=16, verbose_name='State')),
                ('run_after', models.DateTimeField(blank=True, null=True, verbose_name='Run after')),
                ('enqueued_at', models.DateTimeField(auto_now_add=True, verbose_name='Enqueued at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('worker_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Worker')),
                ('claimed_until', models.DateTimeField(blank=True, null=True, verbose_name='Claim expires')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Queued task',
                'verbose_name_plural': 'Queued tasks',
                'ordering': ['-priority', 'enqueued_at'],
                'indexes': [models.Index(fields=['state', 'queue_name', 'run_after'], name='djangocms_a_state_05bc8b_idx'), models.Index(fields=['claimed_until'], name='djangocms_a_claimed_ad2bb4_idx')],
            },
        ),
    ]
