# Generated by Django 6.0rc1 on 2026-08-28 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0013_queuedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationInstanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=20, verbose_name='From status')),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=20, verbose_name='To status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='djangocms_automation.automationinstance', verbose_name='Instance')),
            ],
            options={
                'verbose_name': 'Instance event',
                'verbose_name_plural': 'Instance events',
                'ordering': ['created', 'id'],
            },
        ),
    ]
