# Generated by Django 6.0rc1 on 2026-08-28 23:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
        ('djangocms_automation', '0014_automationinstanceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional comment about this automation step', verbose_name='Comment')),
                ('question', models.CharField(blank=True, help_text="What this loop repeats, e.g. 'While there are unprocessed rows'. Shown in the editor.", max_length=255, verbose_name='Description')),
                ('condition', models.JSONField(default=dict, help_text='Evaluated before every iteration. The loop runs while it is true. Use double curly braces {{ }} for data attribute resolution, e.g. {{ remaining }}.', verbose_name='Condition')),
                ('max_iterations', models.PositiveIntegerField(default=100, help_text='The loop fails once it exceeds this many iterations, rather than running forever.', verbose_name='Maximum iterations')),
            ],
            options={
                'verbose_name': 'Loop Plugin',
                'verbose_name_plural': 'Loop Plugins',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
