# Generated by Django 6.1 on 2026-08-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0015_looppluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='scratch',
            field=models.JSONField(blank=True, default=dict, help_text="Working state a node keeps between re-entries: an agent's conversation so far, its accumulated usage, the tool calls it has dispatched. Private to the node, unlike `result`, which the engine overwrites when a failure propagates.", verbose_name='Scratch state'),
        ),
    ]
