# Generated by Django 6.1 on 2026-08-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0016_automationaction_scratch'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationinstance',
            name='parent_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_instances', to='djangocms_automation.automationaction', verbose_name='Started by'),
        ),
    ]
