# Generated by Django 6.1 on 2026-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0017_instance_parent_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLMActionPluginModel',
        ),
        migrations.CreateModel(
            name='AIStepPluginModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_automation.baseactionpluginmodel',),
        ),
        migrations.AddField(
            model_name='baseactionpluginmodel',
            name='exposed_fields',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Written by the switches beside each input; not edited directly.', verbose_name='Inputs the model may fill'),
        ),
        migrations.AddField(
            model_name='baseactionpluginmodel',
            name='requires_approval',
            field=models.BooleanField(blank=True, default=None, help_text='Pause for a person to approve each call before it runs.', null=True, verbose_name='Requires approval'),
        ),
        migrations.AddField(
            model_name='baseactionpluginmodel',
            name='tool_description',
            field=models.TextField(blank=True, help_text='The only thing telling the model to reach for this rather than something else, and so the setting with the most influence on whether the step works. Say what it does and when to use it — not what it is.', verbose_name='When to use it'),
        ),
        migrations.AddField(
            model_name='baseactionpluginmodel',
            name='tool_name',
            field=models.SlugField(blank=True, help_text="What the model calls this. Defaults to the action's own name.", max_length=64, verbose_name='Called'),
        ),
    ]
