"""Names and help text, plus one alteration that was already outstanding.

``is_active`` and ``name`` gain labels so the admin stops calling the first one
*Is active*. The ``description`` operation is not part of that: the field had
drifted from its last migration before this change, and leaving an app with
pending alterations is worse than carrying an unrelated one here.

Nothing touches the database — all three are metadata.
"""

# Generated by Django 6.1 on 2026-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation', '0020_unique_trigger_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive automations keep their workflow and their history but do not start: timers skip them and their triggers do nothing.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='automationcontent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
