# Generated by Django 6.1 on 2026-09-04 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_automation", "0022_step_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationaction",
            name="context",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="automationaction",
            name="writes",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="automationcontent",
            name="data_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Stable field keys mapped to labels and schemas."
            ),
        ),
        migrations.AddField(
            model_name="automationcontent",
            name="output_fields",
            field=models.JSONField(
                blank=True, default=list, help_text="Fields to return; empty returns the final item."
            ),
        ),
        migrations.AddField(
            model_name="automationinstance",
            name="definition",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="automationinstance",
            name="output",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="automationinstance",
            name="trace_redacted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="baseactionpluginmodel",
            name="outputs",
            field=models.JSONField(blank=True, default=dict, verbose_name="Save result in"),
        ),
        migrations.AddField(
            model_name="looppluginmodel",
            name="iterable",
            field=models.CharField(
                blank=True, help_text="List field for For each.", max_length=255, verbose_name="Use data from"
            ),
        ),
        migrations.AlterField(
            model_name="automationinstance",
            name="automation_content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djangocms_automation.automationcontent",
                verbose_name="Automation Content",
            ),
        ),
        migrations.AlterField(
            model_name="automationinstance",
            name="data",
            field=models.JSONField(default=dict, verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="automationinstance",
            name="initial_data",
            field=models.JSONField(default=dict, verbose_name="Initial Data"),
        ),
        migrations.CreateModel(
            name="ExecutionTrace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurrence", models.UUIDField(db_index=True, null=True)),
                ("kind", models.CharField(max_length=40)),
                ("scope", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("redacted", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace",
                        to="djangocms_automation.automationaction",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
