# Generated by Django 6.1 on 2026-08-29 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional comment about this automation step', verbose_name='Comment')),
                ('question', models.CharField(blank=True, help_text='What this agent is for, shown in the editor.', max_length=255, verbose_name='Description')),
                ('model', models.CharField(help_text='A model string from AUTOMATION_LLM_MODELS, e.g. anthropic/claude-opus-4-8.', max_length=255, verbose_name='Model')),
                ('system_prompt', models.TextField(blank=True, help_text='Standing instructions. Supports {{ dotted.path }} against the automation data.', verbose_name='System prompt')),
                ('prompt', models.TextField(help_text='What to do this run. Supports {{ dotted.path }} against the automation data.', verbose_name='Task')),
                ('max_turns', models.PositiveIntegerField(default=10, verbose_name='Maximum turns')),
                ('max_tool_calls', models.PositiveIntegerField(default=25, verbose_name='Maximum tool calls')),
                ('max_tokens', models.PositiveIntegerField(default=200000, verbose_name='Maximum tokens')),
                ('deadline_seconds', models.PositiveIntegerField(default=900, verbose_name='Deadline (seconds)')),
                ('llm_timeout', models.PositiveIntegerField(default=120, help_text='A hung provider call holds its worker and its lease until something gives up.', verbose_name='Provider timeout (seconds)')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AgentToolPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional comment about this automation step', verbose_name='Comment')),
                ('tool_name', models.SlugField(help_text='What the model calls this tool. Letters, digits, underscore and hyphen.', max_length=64, verbose_name='Tool name')),
                ('tool_description', models.TextField(help_text='What this tool does and when to use it. This is the only thing telling the model when to reach for it, and has more influence on whether an agent works than any other single setting.', verbose_name='Description')),
                ('exposed_fields', models.JSONField(blank=True, default=list, help_text='Field names from the wrapped action. Everything omitted stays bound to the expression you configured on the action and is never offered to the model.', verbose_name='Inputs the model may fill')),
                ('requires_approval', models.BooleanField(default=False, help_text='Pause for a person to approve each call before it runs.', verbose_name='Requires approval')),
            ],
            options={
                'verbose_name': 'Agent tool',
                'verbose_name_plural': 'Agent tools',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
