# Generated by Django 6.1 on 2026-08-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttoolpluginmodel',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='AgentPluginModel',
        ),
        migrations.DeleteModel(
            name='AgentToolPluginModel',
        ),
    ]
