# Generated by Django 6.1 on 2026-08-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_automation_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttoolpluginmodel',
            name='requires_approval',
            field=models.BooleanField(blank=True, default=None, help_text='Pause for a person to approve each call before it runs. Left unset, an action whose effects cannot be taken back requires approval and everything else does not.', null=True, verbose_name='Requires approval'),
        ),
    ]
