# Generated by Django 6.0rc1 on 2026-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("is_published", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ("status", models.CharField(default="received", max_length=32)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
